#################### default parameters ################################
logo = "images/oscar3-logo-trans.png"
logo_width = "200px"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "GitHub"
link = "https://github.com/grycap/oscar"

  
############################# social site ########################
#[[social]]
#title = "facebook"
#icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
#link = "#"

[[social]]
title = "GitHub"
icon = "fab fa-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/grycap/oscar"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/gmolto"

#[[social]]
#title = "skype"
#icon = "fab fa-skype" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[social]]
#title = "linkedin"
#icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"