# This file is for rendering site variables and plugins
# Do not remove this file.
# The presence of this file is for compatibility with Blogdown and Forestry.
# The actual configuration files are stored in the `config/_default/` folder.

######################### Site Variables ##############################
# Customize your color and font from here.
[params.variables]
primary_color = "#95B699"
text_color = "#777"
text_color_dark = "#222"
body_color = "#fff"
border_color = "#777"
black = "#000"
white = "#fff"
light = "#EDF6F5"

# Font variable
# Give your font name from Google Fonts. Add font weight using ":wght@" and separate by ";"
# Example: "Work Sans:wght@400;500;600"
primary_font = "Lato:wght@400"
primary_font_type = "sans-serif"  # [serif/sans-serif]
icon_font = "Font Awesome 5 Free"

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
attributes = "integrity='sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=' crossorigin=''"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"
[[params.plugins.js]]
link = "https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
attributes = "integrity='sha256-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44c=' crossorigin=''"
